name: Java CI with Maven e Notificação por E-mail

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean package

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: maven
      - name: Run Maven tests
        run: mvn test

  email_notification_js:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Instalar dependências
        run: npm install nodemailer

      - name: Executar script de envio de e-mail
        run: node send_email.js
        working-directory: .
        env:
          EMAIL_EDUARDO: ${{ secrets.EMAIL_EDUARDO }}
          SENHA_PRA_EMAIL: ${{ secrets.SENHA_PRA_EMAIL }}
